import { ConfigType } from '../helpers/configType'
import { getConfigs, localizeNodes } from '../helpers/utils'
import { ProviderFactory } from '../llmProviders/providerFactory'

type CustomPrompt = {
    title: string
    prompt: string
}

// Internationalization message management
localizeNodes()

function applyOptionsTheme(themeValue: string): void {
    if (themeValue === 'dark') {
        document.body.setAttribute('data-theme', 'dark')
    }
    else {
        document.body.removeAttribute('data-theme')
    }
}

// Handle AI LLM provider selection event, properly managing what to display
// in the DOM.
document.querySelector('#llmProvider')?.addEventListener('change', (event) => {
    const selectedLlmProvider = (event.target as HTMLInputElement).value

    updateDOMBasedOnSelectLlmProvider(selectedLlmProvider)
})

// Adds an event to update the real-time selection of temperature for the
// output generated by the selected LLM model.
document.querySelector('#llmTemperature')?.addEventListener('input', (event) => {
    const destination = document.querySelector<HTMLInputElement>('label[for=llmTemperature] span')
    const currentTemperatureValue = (event.currentTarget as HTMLInputElement).value
    destination.innerText = Number.parseFloat(currentTemperatureValue).toFixed(2)
})

// Capture all changes in the form fields, disabling the test button.
// This ensures consistency between the edited inputs and the test that
// can be performed by the user, which will always require a prior save.
document.querySelectorAll('#optionsForm input').forEach((node) => {
    node.addEventListener('input', () => {
        document.querySelector<HTMLButtonElement>('#optionsForm button.test').disabled = true
    })
})

document.querySelectorAll('#optionsForm select').forEach((node) => {
    node.addEventListener('change', () => {
        document.querySelector<HTMLButtonElement>('#optionsForm button.test').disabled = true
    })
})

document.querySelector('#theme').addEventListener('change', (event) => {
    applyOptionsTheme((event.target as HTMLSelectElement).value)
})

const customPromptsList = document.querySelector<HTMLDivElement>('#customPromptsList')

document.querySelector('#addCustomPrompt').addEventListener('click', () => {
    appendCustomPromptItem()
    document.querySelector<HTMLButtonElement>('#optionsForm button.test').disabled = true
})

customPromptsList.addEventListener('click', (event: Event) => {
    const target = event.target as HTMLElement
    const item = target.closest('.custom-prompt-item') as HTMLDivElement | null

    if (!item) {
        return
    }

    if (target.classList.contains('custom-prompt-delete')) {
        item.remove()
    }
    else if (target.classList.contains('custom-prompt-up')) {
        const previous = item.previousElementSibling
        if (previous) {
            customPromptsList.insertBefore(item, previous)
        }
    }
    else if (target.classList.contains('custom-prompt-down')) {
        const next = item.nextElementSibling
        if (next) {
            customPromptsList.insertBefore(next, item)
        }
    }

    document.querySelector<HTMLButtonElement>('#optionsForm button.test').disabled = true
})

customPromptsList.addEventListener('input', () => {
    document.querySelector<HTMLButtonElement>('#optionsForm button.test').disabled = true
})
// <-- capture all changes in the form fields, disabling the test button

// Whenever a model is selected, the temperature field availability is
// re-evaluated, since some models do not support a configurable temperature.
document.querySelectorAll('select[id$=Model]').forEach((node) => {
    node.addEventListener('change', updateTemperatureAvailability)
})

// Test management -->
document.querySelector('#optionsForm button.test')?.addEventListener('click', async (event) => {
    // Disable the test button while waiting for the result
    (event.target as HTMLButtonElement).disabled = true;
    (event.target as HTMLButtonElement).classList.add('testing')

    const configs = await getConfigs()
    const llmProvider = ProviderFactory.getInstance(configs)

    llmProvider.testIntegration().then(() => {
        document.querySelector('#optionsForm #testResult').classList.add('ok')
        document.querySelector('#optionsForm #testResult .message').textContent = browser.i18n.getMessage('options.testSuccessful')
    }).catch(error => {
        document.querySelector('#optionsForm #testResult').classList.add('ko')
        document.querySelector('#optionsForm #testResult .message').textContent = error.message
    }).finally(() => {
        document.querySelector<HTMLButtonElement>('#optionsForm button.test').classList.remove('testing')
    })
})

document.querySelector('#testResult .close-icon')?.addEventListener('click', async _ => {
    document.querySelector('#optionsForm #testResult').classList.remove('ok', 'ko')

    // Re-enable the test button as the user has closed the pop-up with the response
    document.querySelector<HTMLButtonElement>('#optionsForm button.test').disabled = false
})
// <-- test management

// Save management
document.querySelector('#optionsForm')?.addEventListener('submit', async (event) => {
    event.preventDefault()

    if (!(event.currentTarget as HTMLFormElement).checkValidity()) {
        (event.currentTarget as HTMLFormElement).classList.add('submit-attempt')

        return
    }

    // Store options -->
    const configs: ConfigType = {
        mainUserLanguageCode: document.querySelector<HTMLInputElement>('#mainUserLanguageCode').value,
        translationLanguageCodes: document.querySelector<MultipleLanguageSelector>('#translationLanguageCodes').getValues(),
        llmProvider: document.querySelector<HTMLInputElement>('#llmProvider').value,
        // A null value is stored when the selected model does not accept the
        // temperature, so that the providers know they must not send it.
        temperature: isTemperatureUnsupported() ? null : Number.parseFloat(document.querySelector<HTMLInputElement>('#llmTemperature').value),
        servicesTimeout: Number.parseInt(document.querySelector<HTMLInputElement>('#servicesTimeout').value),
        streamResponses: document.querySelector<HTMLInputElement>('#streamResponses').checked,
        maskPii: document.querySelector<HTMLInputElement>('#maskPii').checked,
        debugMode: document.querySelector<HTMLInputElement>('#debugMode').checked,
        theme: document.querySelector<HTMLInputElement>('#theme').value,
        customPrompts: getCustomPromptsFromDOM(),
        anthropic: {
            apiKey: document.querySelector<HTMLInputElement>('#anthropicApiKey').value,
            model: document.querySelector<HTMLInputElement>('#anthropicModel').value
        },
        deepseek: {
            apiKey: document.querySelector<HTMLInputElement>('#deepseekApiKey').value,
            model: document.querySelector<HTMLInputElement>('#deepseekModel').value
        },
        google: {
            apiKey: document.querySelector<HTMLInputElement>('#googleApiKey').value,
            model: document.querySelector<HTMLInputElement>('#googleModel').value,
            reasoningEffort: document.querySelector<HTMLSelectElement>('#googleReasoningEffort').value as ConfigType['google']['reasoningEffort']
        },
        groq: {
            apiKey: document.querySelector<HTMLInputElement>('#groqApiKey').value,
            model: document.querySelector<HTMLInputElement>('#groqModel').value
        },
        lms: {
            serviceUrl: document.querySelector<HTMLInputElement>('#lmsServiceUrl').value,
            model: document.querySelector<HTMLInputElement>('#lmsModel').value,
            authToken: document.querySelector<HTMLInputElement>('#lmsAuthToken').value.trim(),
            disableThinking: document.querySelector<HTMLInputElement>('#lmsDisableThinking').checked
        },
        mistral: {
            apiKey: document.querySelector<HTMLInputElement>('#mistralApiKey').value,
            model: document.querySelector<HTMLInputElement>('#mistralModel').value
        },
        ollama: {
            serviceUrl: document.querySelector<HTMLInputElement>('#ollamaServiceUrl').value,
            model: document.querySelector<HTMLInputElement>('#ollamaModel').value,
            reasoningEffort: document.querySelector<HTMLSelectElement>('#ollamaReasoningEffort').value as ConfigType['ollama']['reasoningEffort']
        },
        openai: {
            apiKey: document.querySelector<HTMLInputElement>('#openaiApiKey').value,
            organizationId: document.querySelector<HTMLInputElement>('#openaiOrganizationId').value,
            model: document.querySelector<HTMLInputElement>('#openaiModel').value,
            text2speech: {
                audioQuality: document.querySelector<HTMLInputElement>('#openaiText2SpeechAudioQuality').value,
                voice: document.querySelector<HTMLInputElement>('#openaiText2SpeechVoice').value,
                speed: Number.parseFloat(document.querySelector<HTMLInputElement>('#openaiText2SpeechSpeed').value)
            }
        },
        openaicompatible: {
            serviceUrl: document.querySelector<HTMLInputElement>('#openaicompatibleServiceUrl').value,
            model: document.querySelector<HTMLInputElement>('#openaicompatibleModel').value,
            apiKey: document.querySelector<HTMLInputElement>('#openaicompatibleApiKey').value
        },
        openrouter: {
            apiKey: document.querySelector<HTMLInputElement>('#openrouterApiKey').value,
            model: document.querySelector<HTMLInputElement>('#openrouterModel').value
        },
        vllm: {
            serviceUrl: document.querySelector<HTMLInputElement>('#vllmServiceUrl').value,
            model: document.querySelector<HTMLInputElement>('#vllmModel').value,
            apiKey: document.querySelector<HTMLInputElement>('#vllmApiKey').value
        },
        xai: {
            apiKey: document.querySelector<HTMLInputElement>('#xaiApiKey').value,
            model: document.querySelector<HTMLInputElement>('#xaiModel').value
        }
    }
    // <-- store options

    // Persists the configurations
    await browser.storage.sync.set(configs)
    //logMessage('Storing configurations:\n' + JSON.stringify(await getConfigs(), null, 4))

    // Displaying and turning off the save OK message -->
    document.querySelector('#saveOK').classList.add('show')

    setTimeout(() => {
        document.querySelector('#saveOK').classList.remove('show')
    }, 3000)
    // <-- displaying and turning off the save OK message

    // The test button becomes available only after a correct configuration has
    // been saved.
    document.querySelector('#optionsForm button.test').removeAttribute('disabled')

    // Sends a message named 'optionsChanged' to signal that configurations
    // have been changed, allowing various parts of the application to listen
    // for this message and handle any necessary adjustments.
    browser.runtime.sendMessage({ type: 'optionsChanged' })
})

// Restore options
document.addEventListener('DOMContentLoaded', async _ => {
    const configs = await getConfigs()

    for (const provider of ['anthropic', 'google', 'mistral', 'openai', 'xai', 'deepseek']) {
        const savedModel = configs[provider]?.model
        const select = document.querySelector<HTMLSelectElement>(`#${provider}Model`)
        if (savedModel && select && !Array.from(select.options).some(option => option.value === savedModel)) {
            select.add(new Option(savedModel, savedModel))
        }
    }
    const selectedLlmProvider = configs.llmProvider

    // Temperature -->
    document.querySelector<HTMLInputElement>('#llmTemperature').value = (configs.temperature ?? 0.25).toString()
    document.querySelector<HTMLInputElement>('label[for=llmTemperature] span').innerText = Number.parseFloat(document.querySelector<HTMLInputElement>('#llmTemperature').value).toFixed(2)
    // <-- temperature

    // The language code is retrieved without the regional details (e.g.,
    // 'en-US' becomes just 'en').
    const languageWithRegion = browser.i18n.getUILanguage()
    const languageCode = languageWithRegion.split('-')[0]

    document.querySelector<HTMLInputElement>('#mainUserLanguageCode').value = configs.mainUserLanguageCode || languageCode
    document.querySelector<MultipleLanguageSelector>('#translationLanguageCodes').setValues(configs.translationLanguageCodes || [])
    document.querySelector<HTMLInputElement>('#llmProvider').value = selectedLlmProvider
    document.querySelector<HTMLInputElement>('#servicesTimeout').value = (configs.servicesTimeout || 12).toString()

    // Streaming is the default: the comparison with false, instead of a plain
    // truthy check, keeps it enabled on the installations upgrading from a
    // version where the setting did not exist yet.
    document.querySelector<HTMLInputElement>('#streamResponses').checked = configs.streamResponses === true
    document.querySelector<HTMLInputElement>('#maskPii').checked = configs.maskPii
    document.querySelector<HTMLInputElement>('#debugMode').checked = configs.debugMode
    document.querySelector<HTMLInputElement>('#theme').value = configs.theme || 'default'
    applyOptionsTheme(configs.theme || 'default')
    loadCustomPromptsInDOM(configs.customPrompts || [])

    // Anthropic Claude section -->
    document.querySelector<HTMLInputElement>('#anthropicApiKey').value = configs.anthropic?.apiKey || ''

    if(configs.anthropic?.model) {
        document.querySelector<HTMLInputElement>('#anthropicModel').value = configs.anthropic.model
    }
    // <-- Anthropic Claude section

    // DeepSeek section -->
    document.querySelector<HTMLInputElement>('#deepseekApiKey').value = configs.deepseek?.apiKey || ''

    if(configs.deepseek?.model) {
        document.querySelector<HTMLInputElement>('#deepseekModel').value = configs.deepseek.model
    }
    if (configs.llmProvider === 'deepseek' && !configs.deepseek?.model) {
        document.querySelector<HTMLSelectElement>('#deepseekModel').value = 'deepseek-chat'
    }
    // <-- DeepSeek section

    // Google Gemini section -->
    document.querySelector<HTMLInputElement>('#googleApiKey').value = configs.google?.apiKey || ''

    if(configs.google?.model) {
        document.querySelector<HTMLInputElement>('#googleModel').value = configs.google.model
    }

    if(configs.google?.reasoningEffort) {
        document.querySelector<HTMLInputElement>('#googleReasoningEffort').value = configs.google.reasoningEffort
    }
    // <-- Google Gemini section

    // Groq section -->
    document.querySelector<HTMLInputElement>('#groqApiKey').value = configs.groq?.apiKey || ''
    document.querySelector<HTMLInputElement>('#groqModel').value = configs.groq?.model || ''
    // <-- Groq section

    // LM Studio section -->
    document.querySelector<HTMLInputElement>('#lmsServiceUrl').value = configs.lms?.serviceUrl || 'http://localhost:1234'
    document.querySelector<HTMLInputElement>('#lmsModel').value = configs.lms?.model || ''
    document.querySelector<HTMLInputElement>('#lmsAuthToken').value = configs.lms?.authToken || ''
    document.querySelector<HTMLInputElement>('#lmsDisableThinking').checked = configs.lms?.disableThinking === true
    // <-- LM Studio section

    // Mistral AI section -->
    document.querySelector<HTMLInputElement>('#mistralApiKey').value = configs.mistral?.apiKey || ''

    if(configs.mistral?.model) {
        document.querySelector<HTMLInputElement>('#mistralModel').value = configs.mistral.model
    }
    // <-- Mistral AI section

    // Ollama section -->
    document.querySelector<HTMLInputElement>('#ollamaServiceUrl').value = configs.ollama?.serviceUrl || 'http://localhost:11434'
    document.querySelector<HTMLInputElement>('#ollamaModel').value = configs.ollama?.model || ''

    if(configs.ollama?.reasoningEffort) {
        document.querySelector<HTMLInputElement>('#ollamaReasoningEffort').value = configs.ollama.reasoningEffort
    }
    // <-- Ollama section

    // OpenAI GPT section -->
    document.querySelector<HTMLInputElement>('#openaiApiKey').value = configs.openai?.apiKey || ''
    document.querySelector<HTMLInputElement>('#openaiOrganizationId').value = configs.openai?.organizationId || ''

    if(configs.openai?.model) {
        document.querySelector<HTMLInputElement>('#openaiModel').value = configs.openai.model
    }

    document.querySelector<HTMLInputElement>('#openaiText2SpeechAudioQuality').value = configs.openai?.text2speech?.audioQuality || 'tts-1'
    document.querySelector<HTMLInputElement>('#openaiText2SpeechVoice').value = configs.openai?.text2speech?.voice || 'onyx'
    document.querySelector<HTMLAudioElement>('#openaiText2SpeechVoicePreview audio').setAttribute('src', `https://cdn.openai.com/API/docs/audio/${document.querySelector<HTMLInputElement>('#openaiText2SpeechVoice').value}.wav`)
    document.querySelector<HTMLInputElement>('#openaiText2SpeechSpeed').value = (configs.openai?.text2speech?.speed || 1).toString()
    document.querySelector<HTMLInputElement>('label[for=openaiText2SpeechSpeed] span').innerText = Number.parseFloat(document.querySelector<HTMLInputElement>('#openaiText2SpeechSpeed').value).toFixed(2)
    // <-- OpenAI GPT section

    // OpenAI API compatible section -->
    document.querySelector<HTMLInputElement>('#openaicompatibleServiceUrl').value = configs.openaicompatible?.serviceUrl || 'http://localhost:9931'
    document.querySelector<HTMLInputElement>('#openaicompatibleModel').value = configs.openaicompatible?.model || ''
    document.querySelector<HTMLInputElement>('#openaicompatibleApiKey').value = configs.openaicompatible?.apiKey || ''
    // <-- OpenAI API compatible section

    // OpenRouter section -->
    document.querySelector<HTMLInputElement>('#openrouterApiKey').value = configs.openrouter?.apiKey || ''
    document.querySelector<HTMLInputElement>('#openrouterModel').value = configs.openrouter?.model || ''
    // <-- OpenRouter section

    // vLLM section -->
    document.querySelector<HTMLInputElement>('#vllmServiceUrl').value = configs.vllm?.serviceUrl || 'http://localhost:8000'
    document.querySelector<HTMLInputElement>('#vllmModel').value = configs.vllm?.model || ''
    document.querySelector<HTMLInputElement>('#vllmApiKey').value = configs.vllm?.apiKey || ''
    // <-- vLLM section

    // xAI Grok section -->
    document.querySelector<HTMLInputElement>('#xaiApiKey').value = configs.xai?.apiKey || ''

    if(configs.xai?.model) {
        document.querySelector<HTMLInputElement>('#xaiModel').value = configs.xai.model
    }
    // <-- xAI Grok section

    updateDOMBasedOnSelectLlmProvider(selectedLlmProvider)

    // Check whether at least one of the email accounts in use is based on the "Owl
    // for Exchange" add-on, which has a bug with the messageDisplayScripts API
    // (https://webextension-api.thunderbird.net/en/115/messageDisplayScripts.html)
    // that affects the functionality of this add-on.
    const accountList = await messenger.accounts.list(false)
    if(accountList.some(account => account.type.endsWith('owl'))) {
        document.querySelector('#owlForExchangeBug').classList.add('show')
    }

    // If an LLM provider has been previously saved, the configuration is valid and
    // can potentially be tested, which is why its corresponding button becomes
    // selectable.
    if (selectedLlmProvider) {
        document.querySelector('#optionsForm button.test').removeAttribute('disabled')
    }
    document.dispatchEvent(new Event('optionsRestored'))
})

/**
 * Update the DOM based on the selected LLM provider.
 *
 * @param {string} selectedValue - The selected value
 *
 * @returns {void}
 */
function updateDOMBasedOnSelectLlmProvider(selectedValue: string): void {
    if (!selectedValue) {
        return
    }

    // The possible required attribute of the fields visible to the user is
    // removed.
    document.querySelectorAll('fieldset [required]').forEach((node) => {
        node.removeAttribute('required')
    })

    // Add the required attribute to the fields marked with data-required,
    // ensuring that the user appropriately fills out everything, in
    // accordance with the selected AI LLM service provider.
    document.querySelectorAll(`fieldset#${selectedValue} [data-required]`).forEach((node) => {
        node.setAttribute('required', 'required')
    })

    // The addition of the technical class "data-provider" enhanced by the
    // select, ensures the visibility of the correct section (from CSS rules)
    // for configuring the specific AI LLM service provider.
    document.querySelector('body').setAttribute('data-provider', selectedValue)

    // Once the active provider (and therefore its model selection) is known, the
    // temperature field availability is re-evaluated.
    updateTemperatureAvailability()
}

/**
 * Update the temperature field availability based on the currently selected
 * model.
 *
 * When the selected model option declares the "data-no-temperature" attribute,
 * the temperature is not configurable: the field is locked, a dedicated warning
 * is shown and the value is forced to 1. Otherwise the field is restored to its
 * editable state.
 *
 * @returns {void}
 */
function updateTemperatureAvailability(): void {
    const temperatureInput = document.querySelector<HTMLInputElement>('#llmTemperature')
    const temperatureValueLabel = document.querySelector<HTMLInputElement>('label[for=llmTemperature] span')
    const noTemperatureWarning = document.querySelector('.local-llm-warning-no-temperature')

    if (isTemperatureUnsupported()) {
        // The temperature is locked at 1 and the field is made non-editable.
        if (!temperatureInput.disabled) temperatureInput.dataset.previousValue = temperatureInput.value
        temperatureInput.value = '1'
        temperatureInput.setAttribute('disabled', 'disabled')
        temperatureValueLabel.innerText = Number.parseFloat(temperatureInput.value).toFixed(2)
        noTemperatureWarning.classList.add('show')
    } else {
        if (temperatureInput.disabled && temperatureInput.dataset.previousValue) {
            temperatureInput.value = temperatureInput.dataset.previousValue
            temperatureValueLabel.innerText = Number.parseFloat(temperatureInput.value).toFixed(2)
        }
        temperatureInput.removeAttribute('disabled')
        noTemperatureWarning.classList.remove('show')
    }
}

/**
 * Check whether the currently selected model accepts the temperature parameter.
 *
 * The models that do not accept it declare the "data-no-temperature" attribute
 * on their own option of the model list: this is the single place where the
 * information is maintained, both to lock the field in the options page and to
 * omit the parameter from the requests.
 *
 * @returns {boolean} True when the selected model does not accept the parameter.
 */
function isTemperatureUnsupported(): boolean {
    const selectedProvider = document.querySelector('body').getAttribute('data-provider')
    const modelSelect = selectedProvider ? document.querySelector<HTMLSelectElement>(`#${selectedProvider}Model`) : null
    const selectedModelOption = modelSelect?.selectedOptions?.[0]

    return selectedModelOption?.getAttribute('data-no-temperature') === 'true'
}

function appendCustomPromptItem(customPrompt: CustomPrompt = { title: '', prompt: '' }): void {
    const item = document.createElement('div')
    item.className = 'custom-prompt-item'

    item.innerHTML = `
        <div class="form-group">
            <label data-l10n-ref="options.customPrompts.title"></label>
            <input type="text" class="custom-prompt-title" maxlength="80">
        </div>
        <div class="form-group custom-prompt-textarea-group">
            <label data-l10n-ref="options.customPrompts.prompt"></label>
            <textarea class="custom-prompt-value" rows="3"></textarea>
        </div>
        <div class="custom-prompt-buttons">
            <button type="button" class="custom-prompt-up" data-l10n-ref="options.customPrompts.up"></button>
            <button type="button" class="custom-prompt-down" data-l10n-ref="options.customPrompts.down"></button>
            <button type="button" class="custom-prompt-delete" data-l10n-ref="options.customPrompts.remove"></button>
        </div>
    `

    item.querySelector<HTMLInputElement>('.custom-prompt-title').value = customPrompt.title
    item.querySelector<HTMLTextAreaElement>('.custom-prompt-value').value = customPrompt.prompt
    item.querySelectorAll('[data-l10n-ref]').forEach(node => {
        node.textContent = browser.i18n.getMessage(node.getAttribute('data-l10n-ref'))
    })
    customPromptsList.appendChild(item)
}

function loadCustomPromptsInDOM(customPrompts: CustomPrompt[]): void {
    customPromptsList.innerHTML = ''

    customPrompts.forEach((customPrompt) => {
        appendCustomPromptItem(customPrompt)
    })
}

function getCustomPromptsFromDOM(): CustomPrompt[] {
    return Array.from(customPromptsList.querySelectorAll('.custom-prompt-item'))
        .map((item) => {
            const title = (item.querySelector('.custom-prompt-title') as HTMLInputElement).value.trim()
            const prompt = (item.querySelector('.custom-prompt-value') as HTMLTextAreaElement).value.trim()

            return { title, prompt }
        })
        .filter((customPrompt) => customPrompt.title.length > 0 && customPrompt.prompt.length > 0)
}
